services:

  apache-php:
    build:
      context: .
    container_name: apache-app
    restart: unless-stopped
    networks:
      - default
    ports:
      - 80:80
    depends_on:
      - mysql
    volumes:
      - ./simple-lamp/:/var/www/html/simple-lamp
 
  mysql:
    image: mysql
    container_name: vmysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: simple_lamp
    volumes:
      - ./scriptsql.sh:/docker-entrypoint-initdb.d/scriptsql.sh
      - ./simple-lamp/simple_lamp.sql:/tmp/simple_lamp.sql
    networks:
      - default
    ports:
      - 3306:3306

  memcached:
    image: memcached
    container_name: vmemcached
    networks:
      - default
    ports:
      - 11211:11211

networks:
  default:
    ipam:
      driver: default
      config:
        - subnet: 3.2.1.0/16
  
  


