apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: main-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  tls:
  - hosts:
    - diplom-bobko.dyndns-server.com
    secretName: app-tls
  rules:
   - host: diplom-bobko.dyndns-server.com
     http:
        paths:
          - pathType: Prefix
            path: /
            backend:
              service:
                name: myapp
                port: 
                  number: 80
   
