---
mysql_user: "root"
mysql_root_password: "%18062010Fhntv"
mysql_db_name: "simple_lamp"
app_user: "vanadiy"
http_host: "lamp-app-master"
http_conf: "lamp_app-master.conf"
http_port: "80"
disable_default: true
download_app: "https://github.com/qyjohn/simple-lamp/archive/refs/heads/master.zip"
