---
# tasks file for php
  - name: Set up config.php
    ansible.builtin.template:
      src: "templates/config.php.j2"
      dest: "/var/www/{{ http_host }}/config.php"

  - name: Sets Up PHP Info Page
    template:
      src: "templates/info.php.j2"
      dest: "/var/www/{{ http_host }}/info.php"

  - name: Install memcached
    apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
    loop: [ 'aptitude', 'libmemcached-tools', 'memcached', 'libapache2-mod-php', 'php-memcached', 'php-cli'  ]

  - name: start and enable memcached service
    service:
      name: memcached
      state: started
      enabled: yes