---
# tasks file for lamp-galaxy
    - name: Install prerequisites
      apt: name={{ item }} update_cache=yes state=latest force_apt_get=yes
      loop: [ 'aptitude' ]

    - name: Install LAMP
      apt: name={{ item }} update_cache=yes state=latest
      loop: [ 'python3-pymysql', 'php-mysql', 'libapache2-mod-php', 'unzip', 'php-cli' ]

    - name: Create document root
      file:
        path: "/var/www/{{ http_host }}"
        state: directory
        owner: "{{ app_user }}"
        mode: '0755'

    - name: Sets Up PHP Info Page
      template:
        src: "templates/info.php.j2"
        dest: "/var/www/{{ http_host }}/info.php"

    - name: Download and unarchive zip lamp-app
      ansible.builtin.unarchive:
        src: "{{ download_app }}"
        dest: /var/www/
        remote_src: yes

    - name: Set up Apache virtualhost
      template:
        src: "templates/apache.conf.j2"
        dest: "/etc/apache2/sites-available/{{ http_conf }}"
      notify: Reload Apache

    - name: Ensure the default Apache port 
      ansible.builtin.lineinfile:
        path: /etc/apache2/ports.conf
        regexp: '^Listen '
        insertafter: '^#Listen '
        line: Listen {{ http_port }}

    - name: Disable default Apache site
      shell: /usr/sbin/a2dissite 000-default.conf
      when: disable_default
      notify: Reload Apache

    - name: Change directory owner
      become: true
      ansible.builtin.file:
        state: directory
        path: /var/www/{{ http_host }}/uploads
        owner: www-data
        group: www-data

    - name: Set up config.php
      ansible.builtin.template:
        src: "templates/config.php.j2"
        dest: "/var/www/{{ http_host }}/config.php"

    - name: Enable new site
      shell: /usr/sbin/a2ensite {{ http_conf }}
      notify: Reload Apache