name: Provision infra for Diplpom in GCP

on:
 
  push:
    branches: 
      - develop
  workflow_dispatch:
      
  
     
   
permissions:
  contents: write

jobs:
  Provision-Infra:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./.infra
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v3

      - name: Retrieve the GCP service account secret and save it to a file
        env:
          GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GOOGLE_APPLICATION_CREDENTIALS }}
        run: |
          echo "$GOOGLE_APPLICATION_CREDENTIALS" > service-account.json

      - name: enable API the Google Cloud Console
        run: |
          gcloud auth application-default login
          gcloud config set account babaika.ko@gmail.com
          gcloud config set project singular-glow-405611
          gcloud services enable container.googleapis.com --project=singular-glow-405611
          gcloud services enable container.googleapis.com
          gcloud services enable compute.googleapis.com

      - name: Terraform init
        run: |
          terraform init

      - name: Terraform plan
        run: |
          terraform plan
      
      - name: Terraform apply
        run: |
          terraform apply -auto-approve
